name: Kubernetes CI/CD

on:
    push:
        branches: [main, develop]
        paths:
            - 'infrastructure/kubernetes/**'
    pull_request:
        branches: [main]
        paths:
            - 'infrastructure/kubernetes/**'

env:
    KUBECTL_VERSION: v1.27.0

jobs:
    kubernetes-validate:
        name: Kubernetes Validate
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: ${{ env.KUBECTL_VERSION }}

            - name: Validate Kubernetes manifests
              run: |
                  find infrastructure/kubernetes -name "*.yaml" -o -name "*.yml" | xargs -I {} kubectl apply --dry-run=client --validate=true -f {}

    security-scan-k8s:
        name: Kubernetes Security Scan
        runs-on: ubuntu-latest
        needs: kubernetes-validate
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Run Kubesec
              run: |
                  curl -sSX POST --data-binary @infrastructure/kubernetes/base/backend-deployment.yaml https://v2.kubesec.io/scan
                  curl -sSX POST --data-binary @infrastructure/kubernetes/base/frontend-deployment.yaml https://v2.kubesec.io/scan

            - name: Run Polaris
              uses: fairwindsops/polaris-action@master
              with:
                  config: infrastructure/kubernetes/.polaris.yml
                  path: infrastructure/kubernetes/

    deploy-dev:
        name: Deploy to Development
        runs-on: ubuntu-latest
        needs: [kubernetes-validate, security-scan-k8s]
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        environment: development
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Setup kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: ${{ env.KUBECTL_VERSION }}

            - name: Update kubeconfig
              run: aws eks update-kubeconfig --region us-east-1 --name blockscore-dev-cluster

            - name: Deploy to Kubernetes
              run: |
                  kubectl apply -f infrastructure/kubernetes/base/
                  kubectl set env deployment/blockscore-backend ENVIRONMENT=dev
                  kubectl set env deployment/blockscore-frontend ENVIRONMENT=dev

    deploy-staging:
        name: Deploy to Staging
        runs-on: ubuntu-latest
        needs: [kubernetes-validate, security-scan-k8s]
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        environment: staging
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Setup kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: ${{ env.KUBECTL_VERSION }}

            - name: Update kubeconfig
              run: aws eks update-kubeconfig --region us-east-1 --name blockscore-staging-cluster

            - name: Deploy to Kubernetes
              run: |
                  kubectl apply -f infrastructure/kubernetes/base/
                  kubectl set env deployment/blockscore-backend ENVIRONMENT=staging
                  kubectl set env deployment/blockscore-frontend ENVIRONMENT=staging

    deploy-production:
        name: Deploy to Production
        runs-on: ubuntu-latest
        needs: [kubernetes-validate, security-scan-k8s]
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        environment: production
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
                  aws-region: us-east-1

            - name: Setup kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: ${{ env.KUBECTL_VERSION }}

            - name: Manual Approval Required
              uses: trstringer/manual-approval@v1
              with:
                  secret: ${{ github.TOKEN }}
                  approvers: devops-team,security-team
                  minimum-approvals: 2
                  issue-title: 'Production Kubernetes Deployment Approval'

            - name: Update kubeconfig
              run: aws eks update-kubeconfig --region us-east-1 --name blockscore-prod-cluster

            - name: Deploy to Kubernetes
              run: |
                  kubectl apply -f infrastructure/kubernetes/base/
                  kubectl set env deployment/blockscore-backend ENVIRONMENT=production
                  kubectl set env deployment/blockscore-frontend ENVIRONMENT=production

            - name: Verify Deployment
              run: |
                  kubectl rollout status deployment/blockscore-backend
                  kubectl rollout status deployment/blockscore-frontend
                  kubectl get pods -l app=blockscore-backend
                  kubectl get pods -l app=blockscore-frontend
