---
- name: Install web server packages
  ansible.builtin.package:
    name:
      - nginx
    state: present

- name: Create web application directory
  ansible.builtin.file:
    path: /var/www/{{ app_name }}
    state: directory
    owner: nginx
    group: nginx
    mode: "0755"

- name: Configure Nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/{{ app_name }}.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Nginx

- name: Remove default nginx configuration
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Restart Nginx

- name: Validate nginx configuration
  ansible.builtin.command: nginx -t
  changed_when: false
  register: nginx_validate
  failed_when: nginx_validate.rc != 0

- name: Start and enable Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true

- name: Open HTTP port in firewall
  ansible.posix.firewalld:
    port: "80/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat"

- name: Open HTTPS port in firewall
  ansible.posix.firewalld:
    port: "443/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat"
