---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appName }}-secrets"
type: Opaque
stringData:
  database-url: "{{ .Values.database.url }}"
  redis-url: "redis://{{ .Values.appName }}-redis:{{ .Values.redis.containerPort }}"
  jwt-secret: "{{ .Values.backend.jwtSecret }}"
  mysql-root-password: "{{ .Values.database.rootPassword }}"
  mysql-password: "{{ .Values.database.password }}"
  api-key: "{{ .Values.backend.apiKey }}"
