---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.appName }}-ingress"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.certManager.issuer }}"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/use-regex: "false"
spec:
  ingressClassName: "{{ .Values.ingress.class }}"
  tls:
    - hosts:
        - "{{ .Values.ingress.host }}"
      secretName: "{{ .Values.appName }}-tls"
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.appName }}-backend"
                port:
                  number: { { .Values.backend.servicePort } }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.appName }}-frontend"
                port:
                  number: { { .Values.frontend.servicePort } }
